### ISSUE TITLE
ChatGPT 챗봇 학습 내용 업데이트

### ISSUE THREAD

**Issue by kkn1125** [kkn1125/kkn1125.github.io#50]
1. 블로그 일정 학습
2. 개발자 학습
3. 블로그 정보 학습

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/71887242/226426631-4e4c130e-0ed8-41e7-9e5a-2b3f214f6a3e.png">

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/71887242/226426508-4bf018f4-adfa-4742-bc61-6435cbe6d058.png">

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/71887242/226426688-b176213a-322f-41f6-b6bb-caccde2f741c.png">

**Comment by pg-kkn1125** [comment]
업데이트 완료
현재 블로그 일정 학습 현재부터 2022년 9월 즈음 까지 데이터 학습 완료

**Comment by kkn1125** [comment]
GPT 연결 기능 제거
